development:
  adapter: mysql
  database: dive_development
  username: root
  password: root
  pool: 5
  port: 8889
  host: localhost

production:
  adapter: mysql
  database: turtleba_dive
  username: turtleba
  password: wissfe48
  pool: 5
  port: 8889
  host: localhost
